- permissions/permissions-descriptions_de-DE.json
- permissions/permissions-descriptions_en-US.json
- permissions/permissions-descriptions_es-ES.json
- permissions/permissions-descriptions_fr-FR.json
- permissions/permissions-descriptions_ja-JP.json
- permissions/permissions-descriptions_pt-BR.json
- permissions/permissions-descriptions_ru-RU.json
- permissions/permissions-descriptions_zh-CN.json
- sample-queries/sample-queries_de-DE.json
- sample-queries/sample-queries_en-US.json
- sample-queries/sample-queries_es-ES.json
- sample-queries/sample-queries_fr-FR.json
- sample-queries/sample-queries_ja-JP.json
- sample-queries/sample-queries_pt-BR.json
- sample-queries/sample-queries_ru-RU.json
- sample-queries/sample-queries_zh-CN.json
Proposes:
- Adding copies of the sample queries files and permissions descriptions named with the locale codes that they are to be localized to. This will help during the localization PR, as it would help us easily pick out the diffs.
> Add files for localization

- sample-queries/sample-queries.json
This PR fixes wrong links on the sample queries in the English translation file only
> Fixes wrong links on sample queries

- sample-queries/sample-queries.json
This PR fixes wrong links in sample queries for only the English translated file.
> Fix wrong links in samples queries

- sample-queries/sample-queries.json
This  PR has the following changes:
- Adds 2 Presence samples to Teams.
- Updates Insights and Applications from beta since these samples have since moved to V1.0
- Removes the People sample that's no longer supported. 
Fixes:
#16
> Improving Sample queries quality.

- permissions/permissions-descriptions.json
Updates the scopes descriptions.
> Update scopes descriptions

- permissions/permissions-descriptions.json
Reverts microsoftgraph/microsoft-graph-devx-content#20
> Revert "Update scopes descriptions"

- sample-queries/sample-queries.json
Update profile query to /me/profile and update presence queries' category to users
> Update sample queries

- permissions/permissions-descriptions.json
Huge change alert!
- Adds new permissions scopes, and removes one. 
- Compacts the json structure of the document.
> Update new permissions descriptions from SP

- sample-queries/sample-queries.json
Added the following sample queries for Microsoft Todo
* GET task lists
* POST (create) a new task list
> added sample queries for Microsoft Todo lists

- sample-queries/sample-queries.json
* Adding a sample query for Microsoft To-Do to the **Getting Started** section.
* The query GETs all of the user's task lists.
> Adding a sample query for Microsoft Todo

- sample-queries/sample-queries.json
add more search samples for Microsoft graph search API
> Microsoft search mvp3 postman update

- sample-queries/sample-queries.json
Note: I added the tip using an html tag to make my link clickable, I don't know if this is supported, please check before deploying.
> Added first sample for Identity and Access

- sample-queries/sample-queries.json
Remove Comment section in Post Body.
> fix sort and driveItem in sample-queries

- sample-queries/sample-queries.json
Update the old schema
1. event
2. fields
> Microsoft search mvp3 oldschema fix

- sample-queries/sample-queries.json
standardizing humannames to start with a small letter
> Update humannames property

- permissions/permissions-descriptions.json
- sample-queries/sample-queries.json
- sample-queries/sample-queries_de-DE.json
- sample-queries/sample-queries_es-ES.json
- sample-queries/sample-queries_fr-FR.json
- sample-queries/sample-queries_ja-JP.json
- sample-queries/sample-queries_pt-BR.json
- sample-queries/sample-queries_ru-RU.json
- sample-queries/sample-queries_zh-CN.json
Merges `dev` into `master` to get latest changes into prod.
> Merges dev into master

- sample-queries/sample-queries.json
remove the beta part for shipping to 1.0.
> [MVP4] Ship Microsoft Search to v1.0

- sample-queries/sample-queries.json
Update Microsoft Search to 1.0
> [MVP4] Update Microsoft Search to 1.0

- sample-queries/sample-queries.json
Looking to add a few User GE samples and CES/CVA feedback survey links.
> Add user GE samples and feedback survey

- permissions/permissions-descriptions.json
Manual updates of service principal scopes.
> Update scopes from service principal

- .github/CODEOWNERS
These will be added automatically for all PRs
> Adds repo code owners

- tests/samples.spec.js
- tests/validator.js
Adds a test for the version inside the request URL
Fixes #118
> Feature: test that request version is correct

- sample-queries/sample-queries.json
Currently only feature updates are supported so this sample is better specialized.
> Specialize enrollment sample to feature update management

- sample-queries/sample-queries.json
These operations should have been PATCH not POST.
> Fix update deployment operations to PATCH not POST

- README.md
Updates Readme file with instructions on how to test Sample Queries files on Graph Explorer
> Updates Readme file 

- permissions/permissions-descriptions.json
This PR:
- Manually adds in the permissions descriptions retrieved from the Graph Service Principal
> Adds new permissions descriptions from Service Principal

- sample-queries/sample-queries.json
Add example for Person Search for Microsoft Graph Search API
> Add example for Person Search for Microsoft Graph Search API

- permissions/permissions-beta.json
- permissions/permissions-v1.0.json
This PR updates the the permissions files
> Update permission files

- permissions/permissions-descriptions.json
This PR updates the permissions descriptions from the Graph Service Principal.
> Update permissions descriptions from Service Principal

- sample-queries/sample-queries.json
Reverts microsoftgraph/microsoft-graph-devx-content#195
> Revert "Remove beta claims for speller and result template"

- permissions/permissions-beta.json
- permissions/permissions-v1.0.json
Updates permissions mapping files for v1.0 and beta
> Updates permissions mapping files

- sample-queries/sample-queries.json
> Fix: Add groupType to request body when creating a new group

- sample-queries/sample-queries.json
> Fix: `Create channel` sample tip

- README.md
- Specifies different options of contributing (forking vs cloning) to the different users who want to make a contribution. 
- Updates the support contacts.
> Task: Edit the contribution information and support contacts on the README.md

- README.md
- Focuses more on the forking option of contributing to make it stand out to people with no write access.
> Task: Make changes to the README

- sample-queries/sample-queries.json
Feature Update deployments and Driver Update deployments have a different entry point for add/remove members and exclusions. Creating samples for driver scenario add/remove members and exclusions and updating the existing examples to specify feature update.
> add deployment audience requests driver scenario

- permissions/new/permissions.json
Weekly Permissions sync 2023-03-20
> Weekly Permissions sync 2023-03-20

- permissions/permissions-beta.json
- permissions/permissions-v1.0.json
Update permissions mapping files
> Update permissions mapping files

- sample-queries/sample-queries.json
> Edge APIs to v1.0

- permissions/permissions-beta.json
- permissions/permissions-v1.0.json
Updates for both v1.0 and beta.
> Update request url permissions files

- sample-queries/sample-queries.json
Renaming Teams Targeting sample queries category name to Microsoft Teams Tags to be more user friendly.
> renamed Teams Targeting category name to Microsoft Teams

- permissions/new/permissions.json
Weekly Permissions sync 2023-05-15
> Weekly Permissions sync 2023-05-15

- permissions/new/provisioningInfo.json
Weekly Permissions sync 2023-07-05
> Weekly Permissions sync 2023-07-05

- sample-queries/sample-queries.json
Adding List subdomains and Get subdomains as sample queries
> Add subdomain queries

- sample-queries/sample-queries.json
[WIP]  do not merge this until the code rollout
> update sample queries related to pages API phase 2

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2023-10-04
> Weekly Permissions sync 2023-10-04

- permissions/new/permissions.json
This fixes paths that did not have defined least privilege scopes
> Permission file update

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2023-11-08
> Weekly Permissions sync 2023-11-08

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2023-11-29
> Weekly Permissions sync 2023-11-29

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2023-12-06
> Weekly Permissions sync 2023-12-06

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2023-12-13
> Weekly Permissions sync 2023-12-13

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2023-12-18
> Weekly Permissions sync 2023-12-18

- permissions/new/provisioningInfo.json
Weekly Permissions sync 2023-12-19
> Weekly Permissions sync 2023-12-19

- permissions/new/permissions.json
Weekly Permissions sync 2023-12-20
> Weekly Permissions sync 2023-12-20

- permissions/new/permissions.json
Weekly Permissions sync 2023-12-28
> Weekly Permissions sync 2023-12-28

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2024-01-04
> Weekly Permissions sync 2024-01-04

- permissions/new/permissions.json
Weekly Permissions sync 2024-01-10
> Weekly Permissions sync 2024-01-10

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2024-01-12
> Weekly Permissions sync 2024-01-12

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-01-15
> Weekly Permissions sync 2024-01-15

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-01-16
> Weekly Permissions sync 2024-01-16

- permissions/new/permissions.json
Weekly Permissions sync 2024-01-19
> Weekly Permissions sync 2024-01-19

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-01-22
> Weekly Permissions sync 2024-01-22

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-01-23
> Weekly Permissions sync 2024-01-23

- permissions/new/permissions.json
Weekly Permissions sync 2024-01-24
> Weekly Permissions sync 2024-01-24

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-01-29
> Weekly Permissions sync 2024-01-29

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-01-30
> Weekly Permissions sync 2024-01-30

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-01-31
> Weekly Permissions sync 2024-01-31

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-02-01
> Weekly Permissions sync 2024-02-01

- permissions/new/permissions.json
Weekly Permissions sync 2024-02-06
> Weekly Permissions sync 2024-02-06

- permissions/new/permissions.json
Weekly Permissions sync 2024-02-08
> Weekly Permissions sync 2024-02-08

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-02-12
> Weekly Permissions sync 2024-02-12

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-02-14
> Weekly Permissions sync 2024-02-14

- permissions/new/permissions.json
Weekly Permissions sync 2024-02-15
> Weekly Permissions sync 2024-02-15

- permissions/new/permissions.json
Weekly Permissions sync 2024-02-16
> Weekly Permissions sync 2024-02-16

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-02-19
> Weekly Permissions sync 2024-02-19

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-02-27
> Weekly Permissions sync 2024-02-27

- permissions/new/permissions.json
Weekly Permissions sync 2024-02-28
> Weekly Permissions sync 2024-02-28

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-02-29
> Weekly Permissions sync 2024-02-29

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-01
> Weekly Permissions sync 2024-03-01

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-05
> Weekly Permissions sync 2024-03-05

- permissions/new/permissions.json
Weekly Permissions sync 2024-03-06
> Weekly Permissions sync 2024-03-06

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-08
> Weekly Permissions sync 2024-03-08

- permissions/new/permissions.json
Weekly Permissions sync 2024-03-11
> Weekly Permissions sync 2024-03-11

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-12
> Weekly Permissions sync 2024-03-12

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-13
> Weekly Permissions sync 2024-03-13

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-21
> Weekly Permissions sync 2024-03-21

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-22
> Weekly Permissions sync 2024-03-22

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-25
> Weekly Permissions sync 2024-03-25

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-03-27
> Weekly Permissions sync 2024-03-27

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-04-01
> Weekly Permissions sync 2024-04-01

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-04-05
> Weekly Permissions sync 2024-04-05

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-04-08
> Weekly Permissions sync 2024-04-08

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-04-10
> Weekly Permissions sync 2024-04-10

- permissions/new/permissions.json
Weekly Permissions sync 2024-04-11
> Weekly Permissions sync 2024-04-11

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-04-12
> Weekly Permissions sync 2024-04-12

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-04-15
> Weekly Permissions sync 2024-04-15

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-04-17
> Weekly Permissions sync 2024-04-17

- permissions/new/permissions.json
Weekly Permissions sync 2024-04-18
> Weekly Permissions sync 2024-04-18

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-04-19
> Weekly Permissions sync 2024-04-19

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-04-24
> Weekly Permissions sync 2024-04-24

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-04-25
> Weekly Permissions sync 2024-04-25

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-04-30
> Weekly Permissions sync 2024-04-30

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-05-06
> Weekly Permissions sync 2024-05-06

- permissions/new/permissions.json
Weekly Permissions sync 2024-05-07
> Weekly Permissions sync 2024-05-07

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-05-08
> Weekly Permissions sync 2024-05-08

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-05-14
> Weekly Permissions sync 2024-05-14

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-05-15
> Weekly Permissions sync 2024-05-15

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-05-22
> Weekly Permissions sync 2024-05-22

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-05-23
> Weekly Permissions sync 2024-05-23

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-05-24
> Weekly Permissions sync 2024-05-24

- permissions/new/permissions.json
Weekly Permissions sync 2024-05-29
> Weekly Permissions sync 2024-05-29

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-05-30
> Weekly Permissions sync 2024-05-30

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-06-03
> Weekly Permissions sync 2024-06-03

- permissions/new/permissions.json
Weekly Permissions sync 2024-06-04
> Weekly Permissions sync 2024-06-04

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-06-12
> Weekly Permissions sync 2024-06-12

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-06-13
> Weekly Permissions sync 2024-06-13

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-06-27
> Weekly Permissions sync 2024-06-27

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-06-28
> Weekly Permissions sync 2024-06-28

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-07-01
> Weekly Permissions sync 2024-07-01

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-07-03
> Weekly Permissions sync 2024-07-03

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-07-12
> Weekly Permissions sync 2024-07-12

- sample-queries/sample-queries.json
This will resolve the failing test
> Update invalid sample query doc link

- permissions/new/permissions.json
Weekly Permissions sync 2024-07-15
> Weekly Permissions sync 2024-07-15

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-07-16
> Weekly Permissions sync 2024-07-16

- permissions/new/permissions.json
Weekly Permissions sync 2024-07-29
> Weekly Permissions sync 2024-07-29

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-07-30
> Weekly Permissions sync 2024-07-30

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-07-31
> Weekly Permissions sync 2024-07-31

- permissions/new/permissions.json
Weekly Permissions sync 2024-08-02
> Weekly Permissions sync 2024-08-02

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-05
> Weekly Permissions sync 2024-08-05

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-06
> Weekly Permissions sync 2024-08-06

- permissions/new/permissions.json
Weekly Permissions sync 2024-08-07
> Weekly Permissions sync 2024-08-07

- permissions/new/permissions.json
Weekly Permissions sync 2024-08-09
> Weekly Permissions sync 2024-08-09

- permissions/new/permissions.json
Weekly Permissions sync 2024-08-12
> Weekly Permissions sync 2024-08-12

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-14
> Weekly Permissions sync 2024-08-14

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-19
> Weekly Permissions sync 2024-08-19

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-18
> Weekly Permissions sync 2024-08-18

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-21
> Weekly Permissions sync 2024-08-21

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-20
> Weekly Permissions sync 2024-08-20

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-22
> Weekly Permissions sync 2024-08-22

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-08-23
> Weekly Permissions sync 2024-08-23

- permissions/new/permissions.json
Weekly Permissions sync 2024-08-26
> Weekly Permissions sync 2024-08-26

- permissions/new/permissions.json
Weekly Permissions sync 2024-08-25
> Weekly Permissions sync 2024-08-25

- permissions/new/permissions.json
Weekly Permissions sync 2024-08-24
> Weekly Permissions sync 2024-08-24

- permissions/new/permissions.json
Weekly Permissions sync 2024-08-28
> Weekly Permissions sync 2024-08-28

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-29
> Weekly Permissions sync 2024-08-29

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-08-31
> Weekly Permissions sync 2024-08-31

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-03
> Weekly Permissions sync 2024-09-03

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-04
> Weekly Permissions sync 2024-09-04

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-09-05
> Weekly Permissions sync 2024-09-05

- permissions/new/permissions.json
Weekly Permissions sync 2024-09-06
> Weekly Permissions sync 2024-09-06

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-09-07
> Weekly Permissions sync 2024-09-07

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-08
> Weekly Permissions sync 2024-09-08

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-11
> Weekly Permissions sync 2024-09-11

- permissions/new/permissions.json
Weekly Permissions sync 2024-09-12
> Weekly Permissions sync 2024-09-12

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-13
> Weekly Permissions sync 2024-09-13

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-15
> Weekly Permissions sync 2024-09-15

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-17
> Weekly Permissions sync 2024-09-17

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-09-20
> Weekly Permissions sync 2024-09-20

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-30
> Weekly Permissions sync 2024-09-30

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-29
> Weekly Permissions sync 2024-09-29

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-09-28
> Weekly Permissions sync 2024-09-28

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-10-01
> Weekly Permissions sync 2024-10-01

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-10-08
> Weekly Permissions sync 2024-10-08

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-10-09
> Weekly Permissions sync 2024-10-09

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-10-10
> Weekly Permissions sync 2024-10-10

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-10-11
> Weekly Permissions sync 2024-10-11

- permissions/new/permissions.json
Weekly Permissions sync 2024-10-15
> Weekly Permissions sync 2024-10-15

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-10-22
> Weekly Permissions sync 2024-10-22

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-10-23
> Weekly Permissions sync 2024-10-23

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-10-24
> Weekly Permissions sync 2024-10-24

- permissions/new/permissions.json
Weekly Permissions sync 2024-10-25
> Weekly Permissions sync 2024-10-25

- permissions/new/permissions.json
Weekly Permissions sync 2024-10-26
> Weekly Permissions sync 2024-10-26

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-10-30
> Weekly Permissions sync 2024-10-30

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-11-01
> Weekly Permissions sync 2024-11-01

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-11-04
> Weekly Permissions sync 2024-11-04

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-11-03
> Weekly Permissions sync 2024-11-03

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-11-02
> Weekly Permissions sync 2024-11-02

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-11-05
> Weekly Permissions sync 2024-11-05

- permissions/new/permissions.json
Weekly Permissions sync 2024-11-06
> Weekly Permissions sync 2024-11-06

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-11-07
> Weekly Permissions sync 2024-11-07

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-11-12
> Weekly Permissions sync 2024-11-12

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-11-14
> Weekly Permissions sync 2024-11-14

- permissions/new/permissions.json
Weekly Permissions sync 2024-11-19
> Weekly Permissions sync 2024-11-19

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2024-11-23
> Weekly Permissions sync 2024-11-23

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-11-25
> Weekly Permissions sync 2024-11-25

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-12-03
> Weekly Permissions sync 2024-12-03

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-12-05
> Weekly Permissions sync 2024-12-05

- permissions/new/permissions.json
Weekly Permissions sync 2024-12-06
> Weekly Permissions sync 2024-12-06

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-12-08
> Weekly Permissions sync 2024-12-08

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-12-09
> Weekly Permissions sync 2024-12-09

- permissions/new/permissions.json
Weekly Permissions sync 2024-12-10
> Weekly Permissions sync 2024-12-10

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-12-11
> Weekly Permissions sync 2024-12-11

- permissions/new/permissions.json
Weekly Permissions sync 2024-12-16
> Weekly Permissions sync 2024-12-16

- permissions/new/permissions.json
Weekly Permissions sync 2024-12-14
> Weekly Permissions sync 2024-12-14

- permissions/new/permissions.json
Weekly Permissions sync 2024-12-15
> Weekly Permissions sync 2024-12-15

- permissions/new/permissions.json
Weekly Permissions sync 2024-12-18
> Weekly Permissions sync 2024-12-18

- permissions/new/permissions.json
Weekly Permissions sync 2024-12-20
> Weekly Permissions sync 2024-12-20

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2024-12-30
> Weekly Permissions sync 2024-12-30

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-01-06
> Weekly Permissions sync 2025-01-06

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-01-07
> Weekly Permissions sync 2025-01-07

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-01-09
> Weekly Permissions sync 2025-01-09

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-01-14
> Weekly Permissions sync 2025-01-14

- permissions/new/permissions.json
Weekly Permissions sync 2025-01-15
> Weekly Permissions sync 2025-01-15

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-01-16
> Weekly Permissions sync 2025-01-16

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-01-17
> Weekly Permissions sync 2025-01-17

- permissions/new/permissions.json
Weekly Permissions sync 2025-01-23
> Weekly Permissions sync 2025-01-23

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-01-25
> Weekly Permissions sync 2025-01-25

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-01-26
> Weekly Permissions sync 2025-01-26

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-01-27
> Weekly Permissions sync 2025-01-27

- permissions/new/permissions.json
Weekly Permissions sync 2025-01-28
> Weekly Permissions sync 2025-01-28

- permissions/new/permissions.json
Weekly Permissions sync 2025-01-29
> Weekly Permissions sync 2025-01-29

- permissions/new/permissions.json
Weekly Permissions sync 2025-01-30
> Weekly Permissions sync 2025-01-30

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-01-31
> Weekly Permissions sync 2025-01-31

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-02-04
> Weekly Permissions sync 2025-02-04

- permissions/new/permissions.json
Weekly Permissions sync 2025-02-06
> Weekly Permissions sync 2025-02-06

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-02-07
> Weekly Permissions sync 2025-02-07

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-02-17
> Weekly Permissions sync 2025-02-17

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-02-19
> Weekly Permissions sync 2025-02-19

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-02-20
> Weekly Permissions sync 2025-02-20

- permissions/new/permissions.json
Weekly Permissions sync 2025-02-26
> Weekly Permissions sync 2025-02-26

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-02-28
> Weekly Permissions sync 2025-02-28

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-03-03
> Weekly Permissions sync 2025-03-03

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-03-06
> Weekly Permissions sync 2025-03-06

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-03-11
> Weekly Permissions sync 2025-03-11

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-03-12
> Weekly Permissions sync 2025-03-12

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-03-14
> Weekly Permissions sync 2025-03-14

- permissions/new/permissions.json
Weekly Permissions sync 2025-03-16
> Weekly Permissions sync 2025-03-16

- permissions/new/permissions.json
Weekly Permissions sync 2025-03-18
> Weekly Permissions sync 2025-03-18

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-03-19
> Weekly Permissions sync 2025-03-19

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-03-21
> Weekly Permissions sync 2025-03-21

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-03-23
> Weekly Permissions sync 2025-03-23

- azure-pipelines/publishSamples.yml
Updates the values for the Service Connection in ADO to point to the new content resources in Torus.
> chore: update connection inputs for the pipeline sync stages

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-03-27
> Weekly Permissions sync 2025-03-27

- permissions/new/permissions.json
Weekly Permissions sync 2025-03-28
> Weekly Permissions sync 2025-03-28

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-02
> Weekly Permissions sync 2025-04-02

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-03
> Weekly Permissions sync 2025-04-03

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-04
> Weekly Permissions sync 2025-04-04

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-05
> Weekly Permissions sync 2025-04-05

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-06
> Weekly Permissions sync 2025-04-06

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-07
> Weekly Permissions sync 2025-04-07

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-10
> Weekly Permissions sync 2025-04-10

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-11
> Weekly Permissions sync 2025-04-11

- permissions/new/permissions.json
Weekly Permissions sync 2025-04-15
> Weekly Permissions sync 2025-04-15

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-14
> Weekly Permissions sync 2025-04-14

- permissions/new/permissions.json
Weekly Permissions sync 2025-04-22
> Weekly Permissions sync 2025-04-22

- permissions/new/permissions.json
Weekly Permissions sync 2025-04-23
> Weekly Permissions sync 2025-04-23

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-04-29
> Weekly Permissions sync 2025-04-29

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-05-04
> Weekly Permissions sync 2025-05-04

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-05-07
> Weekly Permissions sync 2025-05-07

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-05-14
> Weekly Permissions sync 2025-05-14

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-05-20
> Weekly Permissions sync 2025-05-20

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-05-21
> Weekly Permissions sync 2025-05-21

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-05-23
> Weekly Permissions sync 2025-05-23

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-05-27
> Weekly Permissions sync 2025-05-27

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-06-03
> Weekly Permissions sync 2025-06-03

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-06-09
> Weekly Permissions sync 2025-06-09

- permissions/new/permissions.json
Weekly Permissions sync 2025-06-13
> Weekly Permissions sync 2025-06-13

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-06-17
> Weekly Permissions sync 2025-06-17

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-06-26
> Weekly Permissions sync 2025-06-26

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-07-01
> Weekly Permissions sync 2025-07-01

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-07-09
> Weekly Permissions sync 2025-07-09

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-07-11
> Weekly Permissions sync 2025-07-11

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-07-30
> Weekly Permissions sync 2025-07-30

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-07-31
> Weekly Permissions sync 2025-07-31

- permissions/permissions-descriptions.json
Update permission description for Contacts SoA permissions
> Update permission description for Contacts SoA permissions

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-08-22
> Weekly Permissions sync 2025-08-22

- permissions/new/ProvisioningInfo.json
Weekly Permissions sync 2025-08-07
> Weekly Permissions sync 2025-08-07

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-08-28
> Weekly Permissions sync 2025-08-28

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-09-01
> Weekly Permissions sync 2025-09-01

- permissions/new/ProvisioningInfo.json
- permissions/new/permissions.json
Weekly Permissions sync 2025-09-22
> Weekly Permissions sync 2025-09-22

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2025-09-23
> Weekly Permissions sync 2025-09-23

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2025-09-25
> Weekly Permissions sync 2025-09-25

- permissions/new/permissions.json
- permissions/new/provisioningInfo.json
Weekly Permissions sync 2025-09-28
> Weekly Permissions sync 2025-09-28

- permissions/new/provisioningInfo.json
Weekly Permissions sync 2025-10-03
> Weekly Permissions sync 2025-10-03
